// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiWaProject.Data;

namespace WebApiWaProject.Migrations
{
    [DbContext(typeof(WaApiContext))]
    [Migration("20210420052330_RunFirst")]
    partial class RunFirst
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("WebApiWaProject.Models.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("Text");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<string>("PlacaVeiculo")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Equipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Essa é a equipe White",
                            Nome = "White",
                            PlacaVeiculo = "AAA1A23"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Essa é a equipe Red",
                            Nome = "Red",
                            PlacaVeiculo = "BBB1B23"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Essa é a equipe Black",
                            Nome = "Black",
                            PlacaVeiculo = "CCC1C23"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Essa é a equipe Blue",
                            Nome = "Blue",
                            PlacaVeiculo = "DDD1D23"
                        });
                });

            modelBuilder.Entity("WebApiWaProject.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("Date");

                    b.Property<string>("Endereco")
                        .HasColumnType("Text");

                    b.Property<int>("EquipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("Pedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrega = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "JOHN SMITH 300 BOYLSTON AVE E SEATTLE WA 98102 USA",
                            EquipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrega = new DateTime(2021, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "JANE ROE 200 E MAIN ST PHOENIX AZ 85123 USA",
                            EquipeId = 2
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2021, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrega = new DateTime(2021, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "MARY ROE MEGASYSTEMS INC 799 E DRAGRAM SUITE 5ATUCSON AZ 85705 USA",
                            EquipeId = 3
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataEntrega = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "CHRIS NISWANDEE SMALLSYS INC 795 E DRAGRAM TUCSON AZ 85705 USA",
                            EquipeId = 4
                        });
                });

            modelBuilder.Entity("WebApiWaProject.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("Text");

                    b.Property<string>("Nome")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80) CHARACTER SET utf8mb4");

                    b.Property<decimal>("Valor")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Flanelas",
                            Nome = "Flanelas",
                            Valor = 2.55m
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Farinha",
                            Nome = "Farinha",
                            Valor = 8.15m
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Óleo",
                            Nome = "Óleo",
                            Valor = 3.50m
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Inseticida",
                            Nome = "Inseticida",
                            Valor = 10.00m
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Algodão",
                            Nome = "Algodão",
                            Valor = 6.75m
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Papel Alumínio",
                            Nome = "Papel Alumínio",
                            Valor = 9.25m
                        });
                });

            modelBuilder.Entity("WebApiWaProject.Models.ProdutoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("Decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoPedidos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PedidoId = 1,
                            ProdutoId = 1,
                            Quantidade = 5,
                            Valor = 12.75m
                        },
                        new
                        {
                            Id = 2,
                            PedidoId = 1,
                            ProdutoId = 2,
                            Quantidade = 2,
                            Valor = 16.30m
                        },
                        new
                        {
                            Id = 3,
                            PedidoId = 1,
                            ProdutoId = 3,
                            Quantidade = 4,
                            Valor = 14.00m
                        },
                        new
                        {
                            Id = 4,
                            PedidoId = 1,
                            ProdutoId = 4,
                            Quantidade = 7,
                            Valor = 70.00m
                        },
                        new
                        {
                            Id = 5,
                            PedidoId = 1,
                            ProdutoId = 5,
                            Quantidade = 3,
                            Valor = 20.25m
                        },
                        new
                        {
                            Id = 6,
                            PedidoId = 1,
                            ProdutoId = 6,
                            Quantidade = 1,
                            Valor = 9.25m
                        },
                        new
                        {
                            Id = 7,
                            PedidoId = 2,
                            ProdutoId = 1,
                            Quantidade = 5,
                            Valor = 12.75m
                        },
                        new
                        {
                            Id = 8,
                            PedidoId = 2,
                            ProdutoId = 2,
                            Quantidade = 2,
                            Valor = 16.30m
                        },
                        new
                        {
                            Id = 9,
                            PedidoId = 2,
                            ProdutoId = 3,
                            Quantidade = 4,
                            Valor = 14.00m
                        },
                        new
                        {
                            Id = 10,
                            PedidoId = 2,
                            ProdutoId = 4,
                            Quantidade = 7,
                            Valor = 70.00m
                        },
                        new
                        {
                            Id = 11,
                            PedidoId = 2,
                            ProdutoId = 5,
                            Quantidade = 3,
                            Valor = 20.25m
                        },
                        new
                        {
                            Id = 12,
                            PedidoId = 2,
                            ProdutoId = 6,
                            Quantidade = 1,
                            Valor = 9.25m
                        },
                        new
                        {
                            Id = 13,
                            PedidoId = 3,
                            ProdutoId = 1,
                            Quantidade = 5,
                            Valor = 12.75m
                        },
                        new
                        {
                            Id = 14,
                            PedidoId = 3,
                            ProdutoId = 2,
                            Quantidade = 2,
                            Valor = 16.30m
                        },
                        new
                        {
                            Id = 15,
                            PedidoId = 3,
                            ProdutoId = 3,
                            Quantidade = 4,
                            Valor = 14.00m
                        },
                        new
                        {
                            Id = 16,
                            PedidoId = 3,
                            ProdutoId = 4,
                            Quantidade = 7,
                            Valor = 70.00m
                        },
                        new
                        {
                            Id = 17,
                            PedidoId = 3,
                            ProdutoId = 5,
                            Quantidade = 3,
                            Valor = 20.25m
                        },
                        new
                        {
                            Id = 18,
                            PedidoId = 3,
                            ProdutoId = 6,
                            Quantidade = 1,
                            Valor = 9.25m
                        },
                        new
                        {
                            Id = 19,
                            PedidoId = 4,
                            ProdutoId = 1,
                            Quantidade = 5,
                            Valor = 12.75m
                        },
                        new
                        {
                            Id = 20,
                            PedidoId = 4,
                            ProdutoId = 2,
                            Quantidade = 2,
                            Valor = 16.30m
                        },
                        new
                        {
                            Id = 21,
                            PedidoId = 4,
                            ProdutoId = 3,
                            Quantidade = 4,
                            Valor = 14.00m
                        },
                        new
                        {
                            Id = 22,
                            PedidoId = 4,
                            ProdutoId = 4,
                            Quantidade = 7,
                            Valor = 70.00m
                        },
                        new
                        {
                            Id = 23,
                            PedidoId = 4,
                            ProdutoId = 5,
                            Quantidade = 3,
                            Valor = 20.25m
                        },
                        new
                        {
                            Id = 24,
                            PedidoId = 4,
                            ProdutoId = 6,
                            Quantidade = 1,
                            Valor = 9.25m
                        });
                });

            modelBuilder.Entity("WebApiWaProject.Models.Pedido", b =>
                {
                    b.HasOne("WebApiWaProject.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("EquipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("WebApiWaProject.Models.ProdutoPedido", b =>
                {
                    b.HasOne("WebApiWaProject.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiWaProject.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
